opendevshop/devshop

playbook.yml

Drush dl failed on installation because git ports are blocked

Change drush download method to wget which allowed behind firewalls

---

install.sh
src/DevShop/Command/Status.php

I accidentally did a lot of work to improve install.sh in 1.x.
Here, I am cherry picking those commits over, trying to avoid the nginx work until that branch is ready.

Backport improvements to install.sh to 0.x

---

tests/features/project.create.feature

This was awesome, I was unable to push to 1.x.
This test shall pass!

I pass the test.

---

docker-development-environment.sh
vagrant-prepare-host.sh

Pulling commits that created the new docker development environment.

Docker dev for 1.x

---

src/DevShop/Console/Command.php

"Fatal error: Call to a member function writeln() on a non-object in /usr/share/devshop/src/DevShop/Console/Command.php on line 266"

Fix github limit fatal error

---

Vagrantfile
playbook.yml
src/DevShop/Console/Application.php
tests/features/project.create.feature
vars.RedHat.yml

See https://travis-ci.org/opendevshop/devshop/jobs/109677322#L1698

Debugging failing tests on CentOS

---

.travis.yml
Vagrantfile
install.sh
playbook.yml
roles/remote/tasks/setup-RedHat.yml
roles/remote/vars/RedHat.yml
vars.RedHat.yml

https://github.com/opendevshop/devmaster/pull/35
CentOS 7 defaults to PHP 5.4
This PR is for getting it updated to 5.5.

Fix CentOS

---

install.sh

provide a reasonable message on failure for unknown OS, and add RHEL in appropriate location for now.

update install.sh with rhel and default

---

install.sh

ansible directory creation and symlink detection... and placeholder for alternative git clone protocol.

update install.sh w directory create and options

---

.travis.yml

travis tests are failing due to language specification needed

added generic language identifier

---

install.sh

if at first you dont succeed...

update install.sh to try https after git/ssh protocol failure

---

install.sh

handle ansible clone a little better

---

install.sh

added pip and related Python modules that needed install.

install from source requires these as well

---

docs/index.md

Fixes display of images on repository home page.

Updated index.md image URLs to use absolute paths.

---

install.sh

last remnant of AEGIR_USER_UID is now banished

remove AEGIR_USER_UID

---

install.sh

check the directory - more universal than which

change the method for detect ansible

---

roles.yml

We need some improvements to the role.  See https://github.com/opendevshop/ansible-role-devmaster
1. The `mysql_root_password` variable in the inventory does not override the playbook.  I'm trying to fix this by putting it in defaults/main.yml instead of vars/main.yml.
2. We need to be able to set "client_email" when installing devmaster, so I added that as a variable.

Improvements to DevMaster role: setting database password, adding client email.

---

.gitignore
.travis.yml
install.sh
roles.yml
tests/test-upgrade.sh

I got a little ahead of myself on that other PR. 
Let's start clean.

Add upgrade test to travis. (ALTERNATE)

---

.travis.yml
RoboFile.php
docker-compose.yml
tests/features/bootstrap/FeatureContext.php
tests/features/project.create.feature

I hate our development-launch.sh scripts.
I love the idea of Robo CLI: http://robo.li
I've replaced the development sh scripts with robo commands!
To use: 
1. Install robo: http://robo.li/robo.phar
2. Run robo in the devshop directory.
```
Robo version 1.0.5
Usage:
command [options] [arguments]
Options:
-h, --help                           Display this help message
-q, --quiet                          Do not output any message
-V, --version                        Display this application version
--ansi                           Force ANSI output
--no-ansi                        Disable ANSI output
-n, --no-interaction                 Do not ask any interactive question
--simulate                       Run in simulated mode (show what would have happened).
--progress-delay=PROGRESS-DELAY …
```

Use Robo CLI for development workflows.

---

RoboFile.php

Trying to reduce test and install times.

Add option to Robofile to make xdebug optional.

---

RoboFile.php
install.sh

This is mainly so we can properly test on docker.

Allow AEGIR_USER_UID to be set using environment variables in install.sh

---

CHANGELOG.md
RoboFile.php

Add removal of development.make.yml file in robo release command.

---

RoboFile.php
build-devmaster-develop.make
build-devmaster.make

Getting confusing to switch git clone with project download in makefile. Let's just create a development makefile.

Create separate Development makefile

---

install.sh

It's been an ansible variable for a long time but I never got around to adding it to the install script.

Add --email option to install.sh script.

---

.travis.yml

Travis suddenly stopped working with docker compose "database" host.

Commenting out docker based tests for now! 

---

build-devmaster-dev.make.yml
install.sh

https://travis-ci.org/opendevshop/devshop/jobs/399299010

Travis started failing for ubuntu 14

---

roles.yml

Updating Roles

---

build-devmaster-dev.make.yml
build-devmaster-travis-forks.make.yml
build-devmaster.make
install.sh
roles.yml
vagrant/Vagrantfile
vagrant/playbook.yml
vagrant/vagrant-prepare-host.sh
vagrant/vars.vagrant.yml

Enable DevShop Support System

---

.travis.yml
install.sh

Reverting part of e305886f965a94818f9136c8a490d53307411a11
@metalbote want to review?

Fixes #337:  put back playbook option.

---

install.sh
src/DevShop/Command/Status.php

Add mentions of opencollective and patreon in the install scripts and status command.

---

.travis.yml
RoboFile.php
ansible.cfg
install.sh
roles.yml

Our 1.x branch started failing after this commit: 93dcdceb4cf1f6f91a5da0cbc271c09facee5c54
I am submitting this PR from that commit to get it to pass, so I can slowly reapply to see what broke the build. 
See https://travis-ci.org/opendevshop/devshop/branches for branch history.

Fix failing CI.

---

CHANGELOG.md
README.md

This PR doesn't change the meaning of things, just the optics.

Documentation: README.md improved slightly 
